#!/usr/bin/env python3
"""Generate the only runtime callout geometry module from reviewed evidence data."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("project", type=Path)
    parser.add_argument("--manifest", default="callouts.targets.json")
    parser.add_argument("--output", default="src/generated-callouts.ts")
    args = parser.parse_args()

    root = args.project.resolve()
    manifest_path = root / args.manifest
    output_path = root / args.output
    raw = manifest_path.read_bytes()
    manifest = json.loads(raw.decode("utf-8-sig"))
    if not isinstance(manifest.get("callouts"), list):
        raise SystemExit("callouts.targets.json needs a callouts array")

    digest = hashlib.sha256(raw).hexdigest()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    payload = json.dumps(
        {"images": manifest.get("images", []), "callouts": manifest["callouts"]},
        ensure_ascii=False,
        indent=2,
    )
    output_path.write_text(
        "// Generated by generate_callouts.py from callouts.targets.json. Do not edit.\n"
        f'export const CALLOUT_MANIFEST_SHA256 = "{digest}";\n\n'
        f"export const generatedEvidence = {payload} as const;\n"
        "export const generatedCallouts = generatedEvidence.callouts;\n"
        "export const generatedEvidenceImages = generatedEvidence.images;\n",
        encoding="utf-8",
    )
    print(f"generated {output_path} from {manifest_path.name} ({digest[:12]})")


if __name__ == "__main__":
    main()
